Vertex.registry.add(0, "broken", null)
Vertex.registry.add(1, "rotator", Vertex.Rotator)
Vertex.registry.add(2, "neuron", Vertex.Neuron)
Vertex.registry.add(3, "feedback", Vertex.Feedback)
Vertex.registry.add(4, "switch", Vertex.Switch)
Vertex.registry.add(5, "min", Vertex.Min)
Vertex.registry.add(6, "max", Vertex.Max)
Vertex.registry.add(7, "inverse", Vertex.Inverse)
