Vertex.registry.add( 0, "none",    Vertex.Base)
Vertex.registry.add( 1, "degree",  Vertex.Degree)
Vertex.registry.add( 2, "rotator", Vertex.Rotator)
Vertex.registry.add( 3, "anchor",  Vertex.Anchor)
Vertex.registry.add( 4, "switch",  Vertex.Switch)
Vertex.registry.add( 5, "meter",   Vertex.Meter)
Vertex.registry.add( 6, "min",     Vertex.Min)
Vertex.registry.add( 7, "max",     Vertex.Max)
Vertex.registry.add( 8, "negate",  Vertex.Negate)
Vertex.registry.add( 9, "sensor",  Vertex.Sensor)
Vertex.registry.add(10, "neuron",  Vertex.Neuron)
//Vertex.registry.add(11, "note", Vertex.Note) TODO
//Vertex.registry.add(11, "charge", Vertex.Charge)
